name: FastTravel
main: net.minebot.fasttravel.FastTravel
version: 0.2
permissions:
    fasttravel.use:
        description: Allows users to find travel points and use them with /ft.
        default: true
    fasttravel.multiworld:
        description: Allows users to use fast travel points located in other worlds.
        default: true
    fasttravel.create:
        description: Allows users to create travel points.
        default: op
    fasttravel.remove.all:
        description: Allows users to remove all travel signs, including those of others.
        default: op
    fasttravel.remove.own:
        description: Allows users to remove their own travel signs.
        default: op
commands:
    ft:
        description: Obtain list of travel points and warp to them
        permission: fasttravel.use
        usage: |
            /ft [travelpoint]