name: FastTravelSigns
main: net.minebot.fasttravel.FastTravelSignsPlugin
version: 0.3
permissions:
    fasttravelsigns.use:
        description: Allows users to find travel points and use them with /ft.
        default: op
    fasttravelsigns.multiworld:
        description: Allows users to use fast travel points located in other worlds.
        default: op
    fasttravelsigns.create:
        description: Allows users to create travel points.
        default: op
    fasttravelsigns.remove.all:
        description: Allows users to remove all travel signs, including those of others.
        default: op
    fasttravelsigns.remove.own:
        description: Allows users to remove their own travel signs.
        default: op
commands:
    ft:
        description: Obtain list of travel points and warp to them
        permission: fasttravelsigns.use
        usage: |
            /ft [travelpoint]